export const RESPONSE_MESSAGES = Object.freeze({
  LOGIN: {
    SUCCESS: 'Login successful',
    ERROR: 'Login failed',
  },
  REGISTER: {
    SUCCESS: 'Register successful',
    ERROR: 'Register failed',
  },
  USER: {
    GET_USER_SUCCESS: 'Get user successful',
    GET_USER_ERROR: 'Get user error',
    GET_PROFILE_SUCCESS: 'Get profile successful',
    GET_PROFILE_ERROR: 'Get profile error',
    UPDATE_USER_STAT_SUCCESS: 'Update user stat successful',
    UPDATE_USER_STAT_ERROR: 'Update user stat error',
    UPDATE_USER_INFO_SUCCESS: 'Update user info successful',
    UPDATE_USER_INFO_ERROR: 'Update user info error',
    EMAIL_EXIST: 'Email already exist',
    CHANGE_PASSWORD_SUCCESS: 'Change password successful',
    CHANGE_PASSWORD_ERROR: 'Change password error',
  },
  RECIPE: {
    GET_RECIPE_SUCCESS: 'Get recipe successful',
    GET_RECIPE_ERROR: 'Get recipe error',
    READY_TO_COOK: 'Ready to cook',
    CAN_NOT_COOK: 'Can not cook this recipe',
    RECOMMEND_FAILED: 'Recommend failed',
    RECOMMEND_SUCCESS: 'Recommend successful',
  },
  INGREDIENT: {
    GET_INGREDIENT_SUCCESS: 'Get ingredient successful',
    GET_INGREDIENT_ERROR: 'Get ingredient error',
    CREATE_INGREDIENT_SUCCESS: 'Create ingredient successful',
    CREATE_INGREDIENT_ERROR: 'Create ingredient error',
    UPDATE_INGREDIENT_SUCCESS: 'Update ingredient successful',
    UPDATE_INGREDIENT_ERROR: 'Update ingredient error',
  },
  RECIPE_RATING: {
    RATING_SUCCESS: 'Rating successful',
    RATING_ERROR: 'Rating error',
  },
  COOKING_HISTORY: {
    GET_COOKING_HISTORY_SUCCESS: 'Get cooking history successful',
    GET_COOKING_HISTORY_ERROR: 'Get cooking history error',
    GET_STATISTICS_SUCCESS: 'Get statistics successful',
    GET_STATISTICS_ERROR: 'Get statistics error',
  },
  DIARY: {
    GET_DIARY_SUCCESS: 'Get diary successful',
    GET_DIARY_ERROR: 'Get diary error',
    CREATE_DIARY_SUCCESS: 'Create diary successful',
    CREATE_DIARY_ERROR: 'Create diary error',
    DELETE_DIARY_SUCCESS: 'Delete diary successful',
    DELETE_DIARY_ERROR: 'Delete diary error',
  },
});
